# Generated by Django 3.1.7 on 2021-03-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='notadeventa',
            name='nota_idMedico',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_apellidoMaterno',
            field=models.CharField(max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_apellidoPaterno',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_cp',
            field=models.CharField(max_length=10, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_direccion',
            field=models.CharField(max_length=250, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_email',
            field=models.CharField(max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_localidad',
            field=models.CharField(max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_municipio',
            field=models.CharField(max_length=100, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_pais',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_tel1',
            field=models.CharField(max_length=10, verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paci_tel2',
            field=models.CharField(max_length=10, null=True, verbose_name='Teléfono 2'),
        ),
        migrations.AddField(
            model_name='notadeventa',
            name='nota_modoPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.modopago'),
        ),
        migrations.AlterField(
            model_name='notadeventa',
            name='nota_statusPago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.status'),
        ),
    ]
