# Generated by Django 3.1.7 on 2021-03-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20210327_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_nombre', models.CharField(max_length=250, verbose_name='Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='notadeventa',
            name='nota_pago',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_apellidoMaterno',
            field=models.CharField(max_length=100, verbose_name='Apellido materno'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_apellidoPaterno',
            field=models.CharField(max_length=100, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_comision',
            field=models.FloatField(verbose_name='Comisión'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_cp',
            field=models.CharField(max_length=10, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_direccion',
            field=models.CharField(max_length=250, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_email',
            field=models.CharField(max_length=250, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_especialidad',
            field=models.CharField(max_length=150, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_localidad',
            field=models.CharField(max_length=100, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_municipio',
            field=models.CharField(max_length=100, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_nombre',
            field=models.CharField(max_length=250, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_pais',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_tel1',
            field=models.CharField(max_length=10, verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='medi_tel2',
            field=models.CharField(max_length=10, null=True, verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='modopago',
            name='modo_nombre',
            field=models.CharField(max_length=250, verbose_name='Modo de pago'),
        ),
        migrations.AlterField(
            model_name='notadeventa',
            name='nota_entrega',
            field=models.CharField(max_length=250, verbose_name='quien recibe'),
        ),
        migrations.AlterField(
            model_name='notadeventa',
            name='nota_fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_nombre',
            field=models.CharField(max_length=250, verbose_name='Estatus'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_nombre', models.CharField(max_length=250, verbose_name='Nombre del servicio')),
                ('serv_precio', models.FloatField(verbose_name='Precio')),
                ('serv_iva', models.FloatField(verbose_name='IVA')),
                ('serv_codigobarra', models.CharField(max_length=250, verbose_name='Codigo de barras')),
                ('serv_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.categoria')),
            ],
        ),
        migrations.AlterField(
            model_name='renglonservicio',
            name='reng_idServicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.servicio'),
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
