# Generated by Django 3.1.7 on 2021-03-28 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20210328_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='renglonservicio',
            name='reng_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.medico'),
        ),
    ]
