# Generated by Django 3.1.7 on 2021-03-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_renglonservicio_reng_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notadeventa',
            name='nota_idUsuario',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
