# Generated by Django 3.1.7 on 2021-04-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_auto_20210331_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='notadeventa',
            name='nota_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='renglonservicio',
            name='reng_monto',
            field=models.FloatField(null=True),
        ),
    ]
